name: Build

on:
  push:
    branches:
      - t-yemekonnen/adding_zlib_support
  pull_request:
    branches:
      - t-yemekonnen/adding_zlib_support
  workflow_dispatch:

jobs:
  build-ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Clang
        run: |
          sudo apt-get update -y -q
          sudo apt-get install -y -q build-essential lsb-release wget software-properties-common
          sudo wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh 15
          sudo apt-get install -y -q libc++-15-dev libc++abi-15-dev
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-15 100
          sudo update-alternatives --install /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-15 100
          sudo update-alternatives --install /usr/bin/ld ld /usr/bin/ld.lld-15 100
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          export CC=clang
          export CXX=clang++
      - name: Install xmake
        run: |
          sudo apt update
          curl -fsSL https://xmake.io/shget.text | bash
      - name: Build with CMake
        run: |
          mkdir -p build && cd build
          export BUILD_SHARED_LIBS=on
          cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
      - name: Upload libleveldb shared library
        uses: actions/upload-artifact@v3
        with:
          path: build/libleveldb.so


  build-macos-gcc:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install xmake
        run: |
          brew install gcc
          export CC=gcc
          export CXX=g++
          curl -fsSL https://xmake.io/shget.text | bash
      - name: Build with CMake
        run: |
          mkdir -p build && cd build
          export BUILD_SHARED_LIBS=on
          cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
      - name: Upload libleveldb shared library
        uses: actions/upload-artifact@v3
        with:
          path: build/libleveldb.dylib
